### ISSUE TITLE
CI: Build of Docker image fails

### ISSUE THREAD

**Issue by uklotzde** [slowtec/openfairdb#521]
The CI build of the Docker image introduced by #520 fails on `main`.

https://github.com/kartevonmorgen/openfairdb/actions/runs/8522344434/job/23349185862

Tests are failing:

```
649.8 failures:
649.8     web::frontend::app_clearance::tests::index_html
649.8     web::frontend::app_clearance::tests::web_fonts
649.8 
649.8 test result: FAILED. 118 passed; 2 failed; 2 ignored; 0 measured; 0 filtered out; finished in 4.73s
```

**Comment by snaeil** [comment]
Sorry for that. I just ran the following again locally (Linux, Manjaro, x86_64):

```sh
docker build --no-cache -t openfairdb:latest .
podman build --no-cache -t openfairdb:latest .
```

Both commands were successful on my machine. I am now trying to see if this has something to do with the workflow.

[This buildx issue](https://github.com/docker/buildx/issues/1986) might be related.

**Comment by snaeil** [comment]
Even this works for me locally:
```sh
docker buildx build -t openfairdb:buildx .
```

**Comment by uklotzde** [comment]
@flosse Any clue why these tests fail when building the image? Do they establish network connections or try to access other, external resources that are not included in the image?

**Comment by snaeil** [comment]
I tried also with running `docker build` explicitly in github actions instead of using the buildx module.
Still failed unfortunately:
```
failures:
     web::frontend::app_clearance::tests::index_html
     web::frontend::app_clearance::tests::web_fonts
```

**Comment by flosse** [comment]
@snaeil I'm very sorry, I really never ever used Docker and I'm also not interested to learn anything about it.
So I will delete the Dockerfile, unless you (or someone else) can imagine taking over the maintenance of it.
I am sorry!

**Comment by snaeil** [comment]
As you wish. I personally try out many projects using official docker builds, if possible.
Since you are not releasing docker images (and there are very good reasons not to), I am opening a PR with a simplified Dockerfile that is not breaking in github actions and that needs much less maintainance.
Downside is missing caching (seems not to be a problem for you currently) and removed testing (but testing is done in your CI already so that you will notice this anyway).

I see your point but I personally would leave the simplified  Dockerfile inside.
